### ISSUE TITLE
tsconfig outDir ./dist

### ISSUE THREAD

**Issue by tb** [ocombe/ng-conf-library#1]
The current code generates compiled files next to the .ts files. You can change it using "outDir": "./dist" in tsconfig "compilerOptions" but then I see errors like:
`{ [Error: ENOENT: no such file or directory, open '/Users/tb/projects/ng-conf-library/test/service.spec.ts.ktp.js']`

You can see that there is dist missing in ktp.js file path.

Do you think outDir: dist/ is good idea? Do you know how to fix it? 😄

**Comment by ocombe** [comment]
You need all the js files to be next to the ts files because you're gonna use imports & exports, and you want it to be consistent between both the ts source files & your js generated files & the sourcemaps. Otherwise you will have problems with people consuming your lib, I think.

So I would say that for a library this is a bad idea :)
